### ISSUE TITLE
运行mvn package遇错

### ISSUE THREAD

**Issue by luckypoem** [net-byte/wsocks#2]
hi.
root@racknerd-7b97d8:~/wsocks-by-net-byte# ls
LICENSE.txt  pom.xml  README.md  wsocks-cli  wsocks-srv
root@racknerd-7b97d8:~/wsocks-by-net-byte# mvn package
[ERROR] Error executing Maven.
[ERROR] java.lang.IllegalStateException: Unable to load cache item
[ERROR] Caused by: Unable to load cache item
[ERROR] Caused by: Could not initialize class com.google.inject.internal.cglib.core.$MethodWrapper
root@racknerd-7b97d8:~/wsocks-by-net-byte# ls
LICENSE.txt  pom.xml  README.md  wsocks-cli  wsocks-srv
root@racknerd-7b97d8:~/wsocks-by-net-byte# cd wsocks-srv
root@racknerd-7b97d8:~/wsocks-by-net-byte/wsocks-srv# ls
Dockerfile  pom.xml  scripts  src
root@racknerd-7b97d8:~/wsocks-by-net-byte/wsocks-srv# mvn package
[ERROR] Error executing Maven.
[ERROR] java.lang.IllegalStateException: Unable to load cache item
[ERROR] Caused by: Unable to load cache item
[ERROR] Caused by: Could not initialize class com.google.inject.internal.cglib.core.$MethodWrapper
root@racknerd-7b97d8:~/wsocks-by-net-byte/wsocks-srv#

怎么解决？

**Comment by net-byte** [comment]
应该是maven 版本与java jdk 版本不匹配。
我的版本没问题：
Openjdk version "11.0.15"
Apache Maven 3.6.3

**Comment by briteming** [comment]
hi.

我卸载了openjdk 18, 然后安装default-jdk(即openjdk 11）：

root@racknerd-7b97d8:~# apt-get install -y default-jdk
正在读取软件包列表... 完成
正在分析软件包的依赖关系树       
正在读取状态信息... 完成       
将会同时安装下列软件：
  default-jdk-headless
下列【新】软件包将被安装：
  default-jdk default-jdk-headless
升级了 0 个软件包，新安装了 2 个软件包，要卸载 0 个软件包，有 170 个软件包未被升级。
需要下载 0 B/2,224 B 的归档。
解压缩后会消耗 12.3 kB 的额外空间。
正在选中未选择的软件包 default-jdk-headless。
(正在读取数据库 ... 系统当前共安装有 71642 个文件和目录。)
正准备解包 .../default-jdk-headless_2%3a1.11-68ubuntu1~18.04.1_amd64.deb  ...
正在解包 default-jdk-headless (2:1.11-68ubuntu1~18.04.1) ...
正在选中未选择的软件包 default-jdk。
正准备解包 .../default-jdk_2%3a1.11-68ubuntu1~18.04.1_amd64.deb  ...
正在解包 default-jdk (2:1.11-68ubuntu1~18.04.1) ...
正在设置 default-jdk-headless (2:1.11-68ubuntu1~18.04.1) ...
正在设置 default-jdk (2:1.11-68ubuntu1~18.04.1) ...
root@racknerd-7b97d8:~# which java
root@racknerd-7b97d8:~# find / -name java
/root/wsocks-by-net-byte/wsocks-cli/src/test/java
/root/wsocks-by-net-byte/wsocks-cli/src/main/java
/root/wsocks-by-net-byte/wsocks-srv/src/test/java
/root/wsocks-by-net-byte/wsocks-srv/src/main/java
/root/cmake-3.23.0-rc2/Tests/CoberturaCoverage/src/main/java
/root/cmake-3.23.0-rc2/Tests/JacocoCoverage/Coverage/src/main/java
/root/cmake-3.23.0-rc2/Testing/CoberturaCoverage/src/main/java
/root/cmake-3.23.0-rc2/Testing/JacocoCoverage/Coverage/src/main/java
root@racknerd-7b97d8:~#
root@racknerd-7b97d8:~# apt-get install -y openjdk-11-jdk openjdk-11-jdk-headless
正在读取软件包列表... 完成
正在分析软件包的依赖关系树       
正在读取状态信息... 完成       
openjdk-11-jdk 已经是最新版 (11.0.15+10-0ubuntu0.18.04.1)。
openjdk-11-jdk-headless 已经是最新版 (11.0.15+10-0ubuntu0.18.04.1)。
升级了 0 个软件包，新安装了 0 个软件包，要卸载 0 个软件包，有 170 个软件包未被升级。
root@racknerd-7b97d8:~# which java
root@racknerd-7b97d8:~# 

活见鬼，竟然安装Openjdk失败了，怎么回事呢？
谢谢回复。

**Comment by luckypoem** [comment]
hi.

服务器端搞定了.我是下载https://github.com/frekele/oracle-java/releases/download/8u92-b14/jdk-8u92-linux-x64.tar.gz，
解压后，设置可执行文件java的环境变量搞定的：
root@racknerd-7b97d8:~# ps aux|grep java
root     31405  0.1 12.5 2976220 256184 ?      Ssl  5月16   1:30 /root/jdk-8u92-linux-x64/jdk1.8.0_92/bin/java -jar wsocks-srv-1.0.0.jar --spring.config.location=application.properties
root     32703  0.0  0.0  16188  1124 pts/0    S+   08:51   0:00 grep --color=auto java
root@racknerd-7b97d8:~#

不过在mac系统上，
yudeMacBook-Air:~ ym$ java -jar wsocks-cli-1.0.0.jar --spring.config.location=wsocks-application.properties
输出：
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.6.6)

2022-05-17 16:09:18.048 ERROR ??? --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.NoClassDefFoundError: Could not initialize class java.net.InetAddress
	at org.springframework.boot.StartupInfoLogger.lambda$appendOn$1(StartupInfoLogger.java:114) ~[spring-boot-2.6.6.jar!/:2.6.6]
	at org.springframework.boot.StartupInfoLogger.callIfPossible(StartupInfoLogger.java:174) ~[spring-boot-2.6.6.jar!/:2.6.6]
	at org.springframework.boot.StartupInfoLogger.append(StartupInfoLogger.java:160) ~[spring-boot-2.6.6.jar!/:2.6.6]
	at org.springframework.boot.StartupInfoLogger.append(StartupInfoLogger.java:156) ~[spring-boot-2.6.6.jar!/:2.6.6]
	at org.springframework.boot.StartupInfoLogger.appendOn(StartupInfoLogger.java:114) ~[spring-boot-2.6.6.jar!/:2.6.6]
	at org.springframework.boot.StartupInfoLogger.getStartingMessage(StartupInfoLogger.java:71) ~[spring-boot-2.6.6.jar!/:2.6.6]
	at org.springframework.core.log.LogMessage$SupplierMessage.buildString(LogMessage.java:155) ~[spring-core-5.3.18.jar!/:5.3.18]
	at org.springframework.core.log.LogMessage.toString(LogMessage.java:70) ~[spring-core-5.3.18.jar!/:5.3.18]
	at java.lang.String.valueOf(String.java:2994) ~[na:1.8.0_92]
	at org.apache.commons.logging.LogAdapter$Slf4jLocationAwareLog.info(LogAdapter.java:454) ~[spring-jcl-5.3.18.jar!/:5.3.18]
	at org.springframework.boot.StartupInfoLogger.logStarting(StartupInfoLogger.java:55) ~[spring-boot-2.6.6.jar!/:2.6.6]
	at org.springframework.boot.SpringApplication.logStartupInfo(SpringApplication.java:624) [spring-boot-2.6.6.jar!/:2.6.6]
	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:385) [spring-boot-2.6.6.jar!/:2.6.6]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:302) [spring-boot-2.6.6.jar!/:2.6.6]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1312) [spring-boot-2.6.6.jar!/:2.6.6]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1301) [spring-boot-2.6.6.jar!/:2.6.6]
	at org.netbyte.Application.main(Application.java:26) [classes!/:1.0.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_92]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_92]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_92]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_92]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) [wsocks-cli-1.0.0.jar:1.0.0]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) [wsocks-cli-1.0.0.jar:1.0.0]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) [wsocks-cli-1.0.0.jar:1.0.0]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) [wsocks-cli-1.0.0.jar:1.0.0]
yudeMacBook-Air:~ ym$
yudeMacBook-Air:~ ym$ java -version
java version "1.8.0_92"
Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)
yudeMacBook-Air:~ ym$

怎么解决这错误？关键是这句话：java.lang.NoClassDefFoundError: Could not initialize class java.net.InetAddress
难道我mac上的java有问题？

非常感谢。

我在windows上，没有问题，可以成功翻墙。windows上的java也是1.8.0版。

**Comment by net-byte** [comment]
java.lang.NoClassDefFoundError: Could not initialize class java.net.InetAddress
Mac 下找不到这个类，试一试其他版本的jdk

**Comment by luckypoem** [comment]
hi.
我删除了 jdk8, 安装了jdk18:
yudeMacBook-Air:~ ym$ java -version
java version "18.0.1.1" 2022-04-22
Java(TM) SE Runtime Environment (build 18.0.1.1+2-6)
Java HotSpot(TM) 64-Bit Server VM (build 18.0.1.1+2-6, mixed mode, sharing)
yudeMacBook-Air:~ ym$ java -jar wsocks-cli-1.0.0.jar --spring.config.location=wsocks-application.properties

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.6.6)

2022-05-17 19:29:41.399 ERROR ??? --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.NoClassDefFoundError: Could not initialize class java.net.InetAddress
	at org.springframework.boot.StartupInfoLogger.lambda$appendOn$1(StartupInfoLogger.java:114) ~[spring-boot-2.6.6.jar!/:2.6.6]
	at org.springframework.boot.StartupInfoLogger.callIfPossible(StartupInfoLogger.java:174) ~[spring-boot-2.6.6.jar!/:2.6.6]
	at org.springframework.boot.StartupInfoLogger.append(StartupInfoLogger.java:160) ~[spring-boot-2.6.6.jar!/:2.6.6]
	at org.springframework.boot.StartupInfoLogger.append(StartupInfoLogger.java:156) ~[spring-boot-2.6.6.jar!/:2.6.6]
	at org.springframework.boot.StartupInfoLogger.appendOn(StartupInfoLogger.java:114) ~[spring-boot-2.6.6.jar!/:2.6.6]
	at org.springframework.boot.StartupInfoLogger.getStartingMessage(StartupInfoLogger.java:71) ~[spring-boot-2.6.6.jar!/:2.6.6]
	at org.springframework.core.log.LogMessage$SupplierMessage.buildString(LogMessage.java:155) ~[spring-core-5.3.18.jar!/:5.3.18]
	at org.springframework.core.log.LogMessage.toString(LogMessage.java:70) ~[spring-core-5.3.18.jar!/:5.3.18]
	at java.base/java.lang.String.valueOf(String.java:4213) ~[na:na]
	at org.apache.commons.logging.LogAdapter$Slf4jLocationAwareLog.info(LogAdapter.java:454) ~[spring-jcl-5.3.18.jar!/:5.3.18]
	at org.springframework.boot.StartupInfoLogger.logStarting(StartupInfoLogger.java:55) ~[spring-boot-2.6.6.jar!/:2.6.6]
	at org.springframework.boot.SpringApplication.logStartupInfo(SpringApplication.java:624) ~[spring-boot-2.6.6.jar!/:2.6.6]
	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:385) ~[spring-boot-2.6.6.jar!/:2.6.6]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:302) ~[spring-boot-2.6.6.jar!/:2.6.6]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1312) ~[spring-boot-2.6.6.jar!/:2.6.6]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1301) ~[spring-boot-2.6.6.jar!/:2.6.6]
	at org.netbyte.Application.main(Application.java:26) ~[classes!/:1.0.0]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:577) ~[na:na]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[wsocks-cli-1.0.0.jar:1.0.0]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[wsocks-cli-1.0.0.jar:1.0.0]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[wsocks-cli-1.0.0.jar:1.0.0]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[wsocks-cli-1.0.0.jar:1.0.0]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: 'void java.net.InetAddress.init()' [in thread "main"]
	at java.base/java.net.InetAddress.init(Native Method) ~[na:na]
	at java.base/java.net.InetAddress.<clinit>(InetAddress.java:362) ~[na:na]
	at java.management/sun.management.VMManagementImpl.getVmId(VMManagementImpl.java:144) ~[na:na]
	at java.management/sun.management.RuntimeImpl.getName(RuntimeImpl.java:59) ~[na:na]
	at org.springframework.boot.system.ApplicationPid.getPid(ApplicationPid.java:54) ~[spring-boot-2.6.6.jar!/:2.6.6]
	at org.springframework.boot.system.ApplicationPid.<init>(ApplicationPid.java:45) ~[spring-boot-2.6.6.jar!/:2.6.6]
	at org.springframework.boot.logging.LoggingSystemProperties.apply(LoggingSystemProperties.java:139) ~[spring-boot-2.6.6.jar!/:2.6.6]
	at org.springframework.boot.logging.logback.LogbackLoggingSystemProperties.apply(LogbackLoggingSystemProperties.java:87) ~[spring-boot-2.6.6.jar!/:2.6.6]
	at org.springframework.boot.logging.LoggingSystemProperties.apply(LoggingSystemProperties.java:134) ~[spring-boot-2.6.6.jar!/:2.6.6]
	at org.springframework.boot.logging.LoggingSystemProperties.apply(LoggingSystemProperties.java:129) ~[spring-boot-2.6.6.jar!/:2.6.6]
	at org.springframework.boot.context.logging.LoggingApplicationListener.initialize(LoggingApplicationListener.java:275) ~[spring-boot-2.6.6.jar!/:2.6.6]
	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEnvironmentPreparedEvent(LoggingApplicationListener.java:240) ~[spring-boot-2.6.6.jar!/:2.6.6]
	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:216) ~[spring-boot-2.6.6.jar!/:2.6.6]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) ~[spring-context-5.3.18.jar!/:5.3.18]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) ~[spring-context-5.3.18.jar!/:5.3.18]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[spring-context-5.3.18.jar!/:5.3.18]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:131) ~[spring-context-5.3.18.jar!/:5.3.18]
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:85) ~[spring-boot-2.6.6.jar!/:2.6.6]
	at org.springframework.boot.SpringApplicationRunListeners.lambda$environmentPrepared$2(SpringApplicationRunListeners.java:66) ~[spring-boot-2.6.6.jar!/:2.6.6]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511) ~[na:na]
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:120) ~[spring-boot-2.6.6.jar!/:2.6.6]
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:114) ~[spring-boot-2.6.6.jar!/:2.6.6]
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:65) ~[spring-boot-2.6.6.jar!/:2.6.6]
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:339) ~[spring-boot-2.6.6.jar!/:2.6.6]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:297) ~[spring-boot-2.6.6.jar!/:2.6.6]
	... 9 common frames omitted

yudeMacBook-Air:~ ym$

还是不行，还是遇到一样的错误：java.lang.NoClassDefFoundError: Could not initialize class java.net.InetAddress
有点匪夷所思。
怎么解决呢？
非常感谢回复！

**Comment by net-byte** [comment]
建议你在mac上自己编译打包jar,我release的jar包是java 11编译的，请用安装java 11,其他版本请自行编译打包。

**Comment by luckypoem** [comment]
hi.

yudeMacBook-Air:~ ym$ git clone https://github.com/net-byte/wsocks wsocks-by-net-byte
yudeMacBook-Air:~ ym$ cd wsocks-by-net-byte
yudeMacBook-Air:wsocks-by-net-byte ym$ mvn -version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /Users/ym/apache-maven-3.6.3-bin/apache-maven-3.6.3
Java version: 18.0.1.1, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk-18.0.1.1.jdk/Contents/Home
Default locale: zh_CN_#Hans, platform encoding: UTF-8
OS name: "mac os x", version: "10.12.6", arch: "x86_64", family: "mac"
yudeMacBook-Air:wsocks-by-net-byte ym$ ls
LICENSE.txt	README.md	pom.xml		wsocks-cli	wsocks-srv
yudeMacBook-Air:wsocks-by-net-byte ym$ mvn package
[INFO] Scanning for projects...
Downloading from central: https://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-starter-parent/2.6.6/spring-boot-starter-parent-2.6.6.pom
...
Exception in thread "main" java.lang.UnsatisfiedLinkError: 'void java.net.InetAddress.init()'
	at java.base/java.net.InetAddress.init(Native Method)
	at java.base/java.net.InetAddress.<clinit>(InetAddress.java:362)
	at org.apache.maven.wagon.providers.http.httpclient.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
	at org.apache.maven.wagon.providers.http.httpclient.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112)
	at org.apache.maven.wagon.providers.http.httpclient.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:374)
	at org.apache.maven.wagon.providers.http.httpclient.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at org.apache.maven.wagon.providers.http.httpclient.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.maven.wagon.providers.http.httpclient.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.maven.wagon.providers.http.httpclient.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.maven.wagon.providers.http.httpclient.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.maven.wagon.providers.http.wagon.shared.AbstractHttpClientWagon.execute(AbstractHttpClientWagon.java:1002)
	at org.apache.maven.wagon.providers.http.wagon.shared.AbstractHttpClientWagon.fillInputData(AbstractHttpClientWagon.java:1160)
	at org.apache.maven.wagon.providers.http.wagon.shared.AbstractHttpClientWagon.fillInputData(AbstractHttpClientWagon.java:1138)
	at org.apache.maven.wagon.StreamWagon.getInputStream(StreamWagon.java:126)
	at org.apache.maven.wagon.StreamWagon.getIfNewer(StreamWagon.java:88)
	at org.apache.maven.wagon.StreamWagon.get(StreamWagon.java:61)
	at org.eclipse.aether.transport.wagon.WagonTransporter$GetTaskRunner.run(WagonTransporter.java:567)
	at org.eclipse.aether.transport.wagon.WagonTransporter.execute(WagonTransporter.java:435)
	at org.eclipse.aether.transport.wagon.WagonTransporter.get(WagonTransporter.java:412)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask(BasicRepositoryConnector.java:457)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:364)
	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:75)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:644)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:262)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:499)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:401)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:229)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:207)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:262)
	at org.apache.maven.project.ProjectModelResolver.resolveModel(ProjectModelResolver.java:192)
	at org.apache.maven.project.ProjectModelResolver.resolveModel(ProjectModelResolver.java:242)
	at org.apache.maven.model.building.DefaultModelBuilder.readParentExternally(DefaultModelBuilder.java:1070)
	at org.apache.maven.model.building.DefaultModelBuilder.readParent(DefaultModelBuilder.java:846)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:337)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:448)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:414)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:377)
	at org.apache.maven.graph.DefaultGraphBuilder.collectProjects(DefaultGraphBuilder.java:414)
	at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor(DefaultGraphBuilder.java:405)
	at org.apache.maven.graph.DefaultGraphBuilder.build(DefaultGraphBuilder.java:82)
	at org.apache.maven.DefaultMaven.buildGraph(DefaultMaven.java:507)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:219)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
yudeMacBook-Air:wsocks-by-net-byte ym$

我在mac上自己编译，还是不行。遇到错误：Exception in thread "main" java.lang.UnsatisfiedLinkError
搜了一下，找到https://www.cnblogs.com/geekHao/p/12820476.html ，没看懂。
能指点一下具体怎么操作吗？
非常感谢。

**Comment by luckypoem** [comment]
装回jdk11, 还是遇到一样的错误。可否开发一个基于go的客户端程序？
非常感谢。

**Comment by net-byte** [comment]
> 装回jdk11, 还是遇到一样的错误。可否开发一个基于go的客户端程序？ 非常感谢。

https://github.com/net-byte/opensocks 用这个
